### PR TITLE
fr localization for /images

### PR DESCRIPTION
**Pull request by Ylkhana**
Created fr folder for images and translated them (except character sheet and locations)
Let the untranslated files as unsure about fallback options

### CODE REVIEW

**Comment by circumspect** [comment]
Merci beaucoup ! Je parle pas assez bien français pour les traduire mais vos traductions me semblent parfaites.

Some comments:
- The image filenames should be the same as they are in english or the bot won't be able to find them (I can fix this)
- Missing images will be replaced with the english versions by default, so it's okay to not have everything
- The bot uses the first message to determine the start of the game, so it should not be paraphrased but rather copy pasted
- I'll make a folder for the krita templates so it's easier for other people to find them, would it be possible for you to add the missing ones after that?

**Comment by Ylkhana** [comment]
My pleasure !

- Thought I fixed the names so they stay the same, my bad. I used some kind of a custom version, made before the localization update, sorry.
- Alright, nice !
- I don't know if it changed a lot, but iirc in previous versions it was triggered by the very beginning of the message. For my games I specified that the message MUST start with "Hey ! Déso de ping tout le monde" (basically "Hey ! Sorry to ping everyone"). If that changes, I'll translate the full message, it's fine !
- Ahah sorry about that, tried to delete them because I was unsure of their usefulness, but I could send the other ones yes, if you think that's helpful.

About that, I also made some very basic cards for #character-cards, in order to show the characters' archetypes without spoiling secrets and messages ([something like that](https://nsa40.casimages.com/img/2021/03/25/210325121749920585.png)), if you think that'd be an interesting addition, I can provide files in en and fr.

**Comment by circumspect** [comment]
No worries! And yeah, the bot only checks the first 20 characters though that's not specified anywhere in the documentation. What matters is that the message being sent matches that in the `LANGUAGE.json` file (under "stuff-for-charlie" -> "first-message"). I think the french.json is the main thing remaining before french language support is complete.

Ooh yeah that would be cool to have, should be easy enough to have the bot send those instead of the normal cards to the character cards channel

**Comment by circumspect** [comment]
Oh btw, your original french fork was what inspired me to add localization support, so thanks haha

**Comment by Ylkhana** [comment]
haha glad it helped, I think my friends would be good enough in english to manage but that's more comfortable this way !
Actually I managed to do it by adding a line in utils.py, adding a folder (e.g. CharaPres) with these pictures and changing the adequate line in... game.py I guess ?
I'll send you the files once the en version is done :)

**Comment by circumspect** [comment]
Sounds good! And it seems I was wrong, the bot does currently require existing images but only for one specific case, so I'll try to fix that

**Pull request merged**
