### PR TITLE
Update french.json

### PR DESCRIPTION
**Pull request by Ylkhana**
- Replaced model link with my own french model
- Added various translations, notably for !help
- Updated commands in Charlie's guidelines
- Updated Charlie's first message for a French, gender-neutral version
- Doesn't really matter but switched the flip data to be accurate :')
Could you clarify the difference between errors "NotACharacter" and "NoCharacterRoles" ? I'm unsure about that and how I should translate them !

### CODE REVIEW

**Comment by circumspect** [comment]
Looks great! Looking back it seems like the two were probably created at different times but can be merged. The difference is one is displayed as an error message when calling the command to remove one's character roles, and the other is displayed when attempting to draw a clue card in manual mode without a character role. I'll delete one and fix the code. Thanks again for everything!

**Comment by circumspect** [comment]
I'm also probably going to remove the private message channels from the json files and just have every server call them "charlie-dakota" etc to make things easier both on the development and the translations end

**Comment by Ylkhana** [comment]
On my server, we talked about the idea of creating whole new sets to make the scenarii and ambiences vary a bit. I thought about creating this sets using localization (even though that's not the main goal), I know it's a very personnal argument but keeping them could be useful ?

**Comment by circumspect** [comment]
Oh I hadn't even thought of that. Sure, I can leave them in until (if) I think of a better way to support that. Though with the "personA-personB" format it should be pretty easy to add more characters

**Pull request merged**
