### PR TITLE
Add text channels with 3+ characters

### PR DESCRIPTION
**Pull request by Hyralc**
A friend told me that it would be a great idea to add private text channels with more than 2 players, like subgroup chats. I made everything in order to change the least things (especially the localization file, concerning the format of the pm channels)

### CODE REVIEW

**Comment by circumspect** [comment]
Thank you for the pull request, and in particular the effort you put into maintaining compatibility! Some thoughts:
- The number of channels each player can see would increase significantly, along with the total number of channels in the server. This would also make it harder for the person running the bot to determine which channels are actually relevant to their character, since they would presumably have server owner and thus be able to see all of the server channels
- (related to the above) This seems like it would add a lot of mostly blank pages to the PDF export if the group chats are used sparingly (i.e., only a few messages/channel). This is still possible in the private channels, but it seems to me that this is more likely to happen in these group chats than in those?
- As much as possible, I'd like the default behavior of the bot to follow the rules of the game as written
- I'm not sure how much this would be used, but since it doesn't seem to change the difficulty of maintaining the bot too much, this isn't necessarily a point against the change

With the above in mind, would it be possible, instead of creating all of the channels at once, to make a command that would allow players to generate these channels on demand? For example, `!gc charlie dakota julia`.

**Comment by Hyralc** [comment]
I agree with pretty much everything you say, but I didn't have a solution, but the one you are suggesting looks really good
As for the blank pages, it should be possible to detect when a channel is empty, therefore to avoid creating a blank page

I agree with the fact that it is great to follow the rules of the games, but i do not understand why you wrote it, is it against the rules to make smaller group chat ?

Also, I was thinking about deleting all the channels concerning a character that is not played at the game start, but maybe it should be an other PR, as you prefer

**Comment by circumspect** [comment]
I'm not sure it's actually written anywhere that you can't, but from what I recall the instructions only mention setting up the group chat and private messages when playing via SMS, and the Discord server template on the Hunters Entertainment website only includes those channels. As a result, I'd prefer it if the bot defaulted to the same behavior unless the particular group of players wants it otherwise.

That's a good point about other players seeing, though I'm not sure how important that is. In any case, I wonder if it's possible to make it so that they can't see previous command uses, either through slash commands (which I think should at least obscure the arguments, i.e., the character names), or by disabling the read message history permission on `bot-channel`. Would either of those work for you?

**Comment by circumspect** [comment]
Oh, that's true, and it would probably also be undesirable for other commands. Deleting the message would work, though!

**Comment by Hyralc** [comment]
I think we agree
I close the PR for now, and when I have the time I will implement what we said and make a new one
Thanks for your comments!

**Pull request closed without merging**
